name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install Dependencies
      run: dotnet restore
    - name: Install Global Tools
      run: dotnet tool restore
    - name: Test
      run: dotnet fake run build.fsx -t Test
